deli-info-list
deli-info-add
deli-info-edit
admin-profile
store-setting
billing-info-delete
billing-info-add
billing-info-edit

dashboard
product-list
product-add
product-detail/{id}
order-list
order-detail/{id}
order-cancel/{id}
customer-list
customer-detail/{id}
customer-block/{id}
